# Generated by Django 5.2.8 on 2026-01-14 14:59

import django.db.models.deletion
import django.db.models.manager
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_title', models.CharField(max_length=66, unique=True, verbose_name='Название жанра')),
                ('genre_slug', models.SlugField(max_length=66, unique=True, verbose_name='Метка жанра')),
                ('genre_description', models.TextField(blank=True, verbose_name='Описание жанра')),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['genre_title'],
            },
        ),
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_first_name', models.CharField(max_length=40, verbose_name='Имя автора')),
                ('author_mid_name', models.CharField(max_length=40, verbose_name='Фамилия автора')),
                ('author_last_name', models.CharField(max_length=40, verbose_name='Отчество автора')),
                ('author_biography', models.TextField(verbose_name='Биография автора')),
                ('author_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover/')),
                ('date_of_birth', models.DateField(null=True, verbose_name='Дата рождения')),
                ('date_of_death', models.DateField(null=True, verbose_name='Дата смерти')),
            ],
            options={
                'verbose_name': 'Автор',
                'ordering': ['-author_mid_name'],
                'indexes': [models.Index(fields=['-author_mid_name'], name='blog_author_author__8722e2_idx')],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(db_index=True, max_length=150, verbose_name='Название книги')),
                ('book_slug', models.SlugField(max_length=150, verbose_name='Метка книги')),
                ('book_status', models.CharField(choices=[('PB', 'Опубликовано')], default='PB', max_length=2, verbose_name='Статус')),
                ('book_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('book_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('book_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover/')),
                ('book_pages', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('book_language', models.CharField(default='Русский', max_length=35, verbose_name='Язык')),
                ('book_description', models.TextField(verbose_name='Описание книги')),
                ('book_age', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('isbn', models.CharField(blank=True, max_length=17, null=True, unique=True, verbose_name='ISBN')),
                ('book_author', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blog_books', to='blog.author', verbose_name='Автор книги')),
                ('book_genre', models.ManyToManyField(related_name='GenrA', to='blog.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга',
                'verbose_name_plural': 'Книги',
                'ordering': ['-book_publish'],
            },
            managers=[
                ('book_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250, verbose_name='Название')),
                ('slug', models.SlugField(max_length=250, verbose_name='Метка')),
                ('body', models.TextField(verbose_name='Содержание')),
                ('publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликован')], default='DF', max_length=2, verbose_name='Статус')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-publish'],
            },
            managers=[
                ('published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name='Рейтинг')),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_rating', to='blog.book')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rate', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_book_title', models.CharField(db_index=True, max_length=100, verbose_name='Название книги')),
                ('user_book_slug', models.SlugField(max_length=100, verbose_name='Метка книги')),
                ('user_book_body', models.TextField(verbose_name='Содержание книги')),
                ('user_book_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('user_book_created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user_book_update', models.DateTimeField(auto_now=True, verbose_name='Дата изменения')),
                ('user_book_status', models.CharField(choices=[('DF', 'Черновик'), ('PB', 'Опубликовано')], default='DF', max_length=2, verbose_name='Статус')),
                ('user_book_cover', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover/')),
                ('user_book_pages', models.PositiveIntegerField(default=0, verbose_name='Количество страниц')),
                ('user_book_language', models.CharField(default='Русский', max_length=35, verbose_name='Язык')),
                ('user_book_description', models.TextField(verbose_name='Описание книги')),
                ('user_book_age', models.PositiveIntegerField(default=0, verbose_name='Возрастное ограничение')),
                ('user_book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_user_books', to=settings.AUTH_USER_MODEL, verbose_name='Автор книги')),
                ('user_book_genre', models.ManyToManyField(related_name='GenrU', to='blog.genre', verbose_name='Жанр')),
            ],
            options={
                'verbose_name': 'Книга пользователя',
                'verbose_name_plural': 'Книги пользователей',
                'ordering': ['-user_book_publish'],
            },
            managers=[
                ('user_book_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Commentary_Book_Write',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_user_book_body', models.TextField(verbose_name='комментарий')),
                ('comment_user_book_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('comment_user_book_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('comment_user_book_status', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('comment_user_book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_user_book_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('comment_book_write', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentsBW', to='blog.userbook', verbose_name='Комментарий под книгу:')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комметарии',
                'ordering': ['-comment_user_book_publish'],
            },
            managers=[
                ('comment_user_book_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.CreateModel(
            name='Commentary_Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_book_body', models.TextField(verbose_name='комментарий')),
                ('comment_book_publish', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('comment_book_update', models.DateTimeField(auto_now_add=True, verbose_name='Дата обновления')),
                ('comment_book_status', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('comment_book', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CommentsB', to='blog.book', verbose_name='Комментарий под книгу:')),
                ('comment_book_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_book_author', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарии',
                'verbose_name_plural': 'Комметарии',
                'ordering': ['-comment_book_publish'],
                'indexes': [models.Index(fields=['-comment_book_publish'], name='blog_commen_comment_7c8956_idx')],
            },
            managers=[
                ('comment_book_published', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddIndex(
            model_name='book',
            index=models.Index(fields=['-book_publish'], name='blog_book_book_pu_1dcb5e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-publish'], name='blog_post_publish_bb7600_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('book', 'user')},
        ),
        migrations.AddIndex(
            model_name='userbook',
            index=models.Index(fields=['-user_book_publish'], name='blog_userbo_user_bo_405649_idx'),
        ),
        migrations.AddIndex(
            model_name='commentary_book_write',
            index=models.Index(fields=['-comment_user_book_publish'], name='blog_commen_comment_646a12_idx'),
        ),
    ]
