# Generated by Django 5.2.8 on 2026-03-23 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edit_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='Никнейм')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='', verbose_name='cover/')),
                ('birthday', models.DateField(auto_now_add=True, verbose_name='Дата рождения')),
            ],
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
    ]
