# Generated by Django 5.2.8 on 2026-03-24 14:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_author_author_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='book',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='edit_profile',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover'),
        ),
        migrations.AlterField(
            model_name='edit_profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='blog/avatars'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='blog/cover'),
        ),
    ]
