# Generated by Django 5.2.8 on 2026-03-24 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_book_managers_edit_profile_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.IntegerField(blank=True, null=True, unique=True, verbose_name='ID'),
        ),
    ]
