# Generated by Django 5.2.8 on 2026-03-29 16:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_book_book_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_ratings',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='blog.rating'),
        ),
        migrations.AddField(
            model_name='rating',
            name='avg_rating',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=3),
        ),
        migrations.AlterField(
            model_name='author',
            name='author_image',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='edit_profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='blog.book'),
        ),
        migrations.AlterField(
            model_name='rating',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 - плохо'), (2, '2 - не очень'), (3, '3 - сойдет'), (4, '4 - хорошо'), (5, '5 - отлично')]),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='cover/'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_book_description',
            field=models.TextField(max_length=2000, verbose_name='Описание книги'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_book_slug',
            field=models.SlugField(max_length=200, verbose_name='Метка книги'),
        ),
        migrations.AlterField(
            model_name='userbook',
            name='user_book_title',
            field=models.CharField(db_index=True, max_length=200, verbose_name='Название книги'),
        ),
    ]
