# Generated by Django 5.2.8 on 2026-03-30 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_book_book_ratings_rating_avg_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='book_ratings',
        ),
    ]
