# Generated by Django 5.2.8 on 2026-05-04 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_book_book_ratings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='edit_profile',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
